// CRMFormFields.ts
import { IFormField } from "../../utils/form_factory";
import { LEAD_STATUS_OPTIONS, ACCOUNT_TYPE_OPTIONS, OPPORTUNITY_STAGE_OPTIONS, CONTRACT_STATUS_OPTIONS, LEAD_SOURCE_OPTIONS } from "./CRM.interface";

// Lead Form Fields
export const LeadFormFields = (bdmOptions: any[] = []): IFormField[] => [
  {
    name: 'name',
    initailValue: '',
    label: 'Lead Name',
    type: 'text',
    uiType: 'text',
    uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
    required: true,
  },
  {
    name: 'phone',
    initailValue: '',
    label: 'Phone Number',
    type: 'tel',
    uiType: 'phone',
    uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
    required: true,
  },
  {
    name: 'email',
    initailValue: '',
    label: 'Email Address',
    type: 'email',
    uiType: 'email',
    uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
  },
  {
    name: 'source',
    initailValue: '',
    label: 'Lead Source',
    type: 'select',
    uiType: 'select',
    options: LEAD_SOURCE_OPTIONS,
    uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
    required: true,
  },
  {
    name: 'status',
    initailValue: 'new',
    label: 'Status',
    type: 'select',
    uiType: 'select',
    options: LEAD_STATUS_OPTIONS,
    uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
    required: true,
  },
  {
    name: 'assigned_to_id',
    initailValue: '',
    label: 'Assign to BDM',
    type: 'select',
    uiType: 'select',
    options: bdmOptions,
    uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
  },
];

// Account Form Fields
export const AccountFormFields = (hubOptions: any[] = []): IFormField[] => [
  {
    name: 'name',
    initailValue: '',
    label: 'Account Name',
    type: 'text',
    uiType: 'text',
    uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
    required: true,
  },
  {
    name: 'type',
    initailValue: '',
    label: 'Account Type',
    type: 'select',
    uiType: 'select',
    options: ACCOUNT_TYPE_OPTIONS,
    uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
    required: true,
  },
  {
    name: 'credit_terms_days',
    initailValue: 30,
    label: 'Credit Terms (Days)',
    type: 'number',
    uiType: 'number',
    uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
    required: true,
  },
  {
    name: 'hub_id',
    initailValue: '',
    label: 'Hub',
    type: 'select',
    uiType: 'select',
    options: hubOptions,
    uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
  },
];

// Contact Form Fields
export const ContactFormFields = (accountOptions: any[] = [], userOptions: any[] = []): IFormField[] => [
  {
    name: 'name',
    initailValue: '',
    label: 'Contact Name',
    type: 'text',
    uiType: 'text',
    uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
    required: true,
  },
  {
    name: 'phone',
    initailValue: '',
    label: 'Phone Number',
    type: 'tel',
    uiType: 'phone',
    uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
    required: true,
  },
  {
    name: 'email',
    initailValue: '',
    label: 'Email Address',
    type: 'email',
    uiType: 'email',
    uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
  },
  {
    name: 'role',
    initailValue: '',
    label: 'Role/Position',
    type: 'text',
    uiType: 'text',
    uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
  },
  {
    name: 'account_id',
    initailValue: '',
    label: 'Account',
    type: 'select',
    uiType: 'select',
    options: accountOptions,
    uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
    required: true,
  },
  {
    name: 'user_id',
    initailValue: '',
    label: 'Link to BDM User',
    type: 'select',
    uiType: 'select',
    options: userOptions,
    uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
  },
];

// Opportunity Form Fields
export const OpportunityFormFields = (accountOptions: any[] = [], bdmOptions: any[] = []): IFormField[] => [
  {
    name: 'name',
    initailValue: '',
    label: 'Opportunity Name',
    type: 'text',
    uiType: 'text',
    uiBreakpoints: { xs: 12, sm: 12, md: 12, lg: 12, xl: 12 },
    required: true,
  },
  {
    name: 'account_id',
    initailValue: '',
    label: 'Account',
    type: 'select',
    uiType: 'select',
    options: accountOptions,
    uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
    required: true,
  },
  {
    name: 'expected_volume_mt',
    initailValue: '',
    label: 'Expected Volume (MT)',
    type: 'number',
    uiType: 'number',
    uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
    required: true,
  },
  {
    name: 'expected_price_per_mt',
    initailValue: '',
    label: 'Expected Price per MT ($)',
    type: 'number',
    uiType: 'number',
    uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
    required: true,
  },
  {
    name: 'stage',
    initailValue: 'prospect',
    label: 'Stage',
    type: 'select',
    uiType: 'select',
    options: OPPORTUNITY_STAGE_OPTIONS,
    uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
    required: true,
  },
  {
    name: 'assigned_to_id',
    initailValue: '',
    label: 'Assign to BDM',
    type: 'select',
    uiType: 'select',
    options: bdmOptions,
    uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
    required: true,
  },
];

// Contract Form Fields
export const ContractFormFields = (opportunityOptions: any[] = []): IFormField[] => [
  {
    name: 'opportunity_id',
    initailValue: '',
    label: 'Opportunity',
    type: 'select',
    uiType: 'select',
    options: opportunityOptions,
    uiBreakpoints: { xs: 12, sm: 12, md: 12, lg: 12, xl: 12 },
    required: true,
  },
  {
    name: 'terms',
    initailValue: '',
    label: 'Contract Terms',
    type: 'text',
    uiType: 'textarea',
    uiBreakpoints: { xs: 12, sm: 12, md: 12, lg: 12, xl: 12 },
    required: true,
  },
  {
    name: 'status',
    initailValue: 'draft',
    label: 'Status',
    type: 'select',
    uiType: 'select',
    options: CONTRACT_STATUS_OPTIONS,
    uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
    required: true,
  },
  {
    name: 'signed_at',
    initailValue: '',
    label: 'Signed Date',
    type: 'datetime-local',
    uiType: 'datetime',
    uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
  },
];