import { IFormField } from "../../../utils/form_factory";
import { CURRENCY_CODES } from "../../../constants/currency-codes";
import { INVESTMENT_TYPES, INTEREST_TYPES, DURATION_UNITS, REPAYMENT_FREQUENCIES, RISK_LEVELS, COLLATERAL_TYPES, ELIGIBLE_INVESTOR_TYPES, VISIBILITY_OPTIONS, BORROWER_TYPES } from "../../../constants/investment-options";
import { es } from "date-fns/locale";
import { IGeneralFormProps } from "../../Investments/InvestmentsList/Investment.interface";



export const GeneralFormFields = (
  INVESTMENT_TYPES: any[],
  INTEREST_TYPES: any[],
  DURATION_UNITS: any[],
  REPAYMENT_FREQUENCIES: any[],
  banks: { value: string; label: string }[],
  handleBankSearch: (query: string) => void
): IFormField[] => [

  {
    name: "investment_name",
    initailValue: "",
    label: "Investment Name",
    type: "text",
    uiType: "text",
    uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
  },
  {
    name: "investment_bank",
    initailValue: "",
    label: "Investment Bank",
    type: "text",
    uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
    uiType: "select",
    options: banks,
    handleSearch: handleBankSearch
  },
  {
    name: "investment_type",
    initailValue: "",
    label: "Investment Type",
    type: "text",
    uiType: "select",
    uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
    options: INVESTMENT_TYPES,
  },
  {
    name: "investment_description",
    initailValue: "",
    label: "Investment Description",
    type: "text",
    uiType: "textarea",
    uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
    multiline: true,
    rows: 3,
  },
  {
    name: "investment_code",
    initailValue: "",
    label: "Investment Code",
    type: "text",
    uiType: "text",
    uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
  },
  {
    name: "total_investment_amount",
    initailValue: "",
    label: "Total Investment Amount",
    type: "number",
    uiType: "number",
    uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
  },
  {
    name: "available_units",
    initailValue: "",
    label: "Available Units",
    type: "number",
    uiType: "number",
    uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
  },
  {
    name: "unit_price",
    initailValue: "",
    label: "Unit Price",
    type: "number",
    uiType: "number",
    uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
  },
  {
    name: "minimum_investment_amount",
    initailValue: "",
    label: "Minimum Investment Amount",
    type: "number",
    uiType: "number",
    uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
  },
  {
    name: "maximum_investment_amount",
    initailValue: "",
    label: "Maximum Investment Amount",
    type: "number",
    uiType: "number",
    uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
  },
  {
    name: "interest_rate",
    initailValue: "",
    label: "Interest Rate (%)",
    type: "number",
    uiType: "number",
    uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
  },
  {
    name: "interest_type",
    initailValue: "",
    label: "Interest Type",
    type: "text",
    uiType: "select",
    uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
    options: INTEREST_TYPES,
  },
  {
    name: "investment_duration_value",
    initailValue: "",
    label: "Investment Duration",
    type: "number",
    uiType: "number",
    uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
  },
  {
    name: "investment_duration_unit",
    initailValue: "",
    label: "Duration Unit",
    type: "text",
    uiType: "select",
    uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
    options: DURATION_UNITS,
  },
  {
    name: "repayment_frequency",
    initailValue: "",
    label: "Repayment Frequency",
    type: "text",
    uiType: "select",
    uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
    options: REPAYMENT_FREQUENCIES,
  },
  {
    name: "start_date",
    initailValue: "",
    label: "Start Date",
    type: "date",
    uiType: "date",
    uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
  },
  {
    name: "end_date",
    initailValue: "",
    label: "End Date",
    type: "date",
    uiType: "date",
    uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
  },
];

export const SettingsFormFields = (
  RISK_LEVELS: any[],
  COLLATERAL_TYPES: any[],
  CURRENCY_CODES: any[],
  ELIGIBLE_INVESTOR_TYPES: any[],
  VISIBILITY_OPTIONS: any[],
): IFormField[] => [
  {
    name: "risk_level",
    initailValue: "",
    label: "Risk Level",
    type: "text",
    uiType: "select",
    uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
    options: RISK_LEVELS,
  },
  {
    name: "guarantee_principal",
    initailValue: false,
    label: "Guarantee Principal",
    type: "boolean",
    uiType: "switch",
    uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
  },
  {
    name: "collateral_type",
    initailValue: "",
    label: "Collateral Type",
    type: "text",
    uiType: "select",
    uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
    options: COLLATERAL_TYPES,
  },
  { name: "collateral_value", 
    initailValue: "", 
    label: "Collateral Value", 
    type: "number", 
    uiType: "number", 
    uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 }
  },
  {
    name: "platform_fee",
    initailValue: "",
    label: "Platform Fee (%)",
    type: "number",
    uiType: "number",
    uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
  },
  
  { name: "early_termination_fee",
    initailValue: "",
    label: "Early Termination Fee",
    type: "number",
    uiType: "number",
    uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 }
  },
  {
    name: "withdrawal_before_maturity",
    initailValue: false,
    label: "Withdrawal Before Maturity",
    type: "boolean",
    uiType: "switch",
    uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
  },
  {
    name: "transferability_of_units",
    initailValue: false,
    label: "Transferability of Units",
    type: "boolean",
    uiType: "switch",
    uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
  },
  {
    name: "currency",
    initailValue: "",
    label: "Currency",
    type: "text",
    uiType: "select",
    uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
    options: CURRENCY_CODES,
  },
  {
    name: "eligible_investor_type",
    initailValue: "",
    label: "Eligible Investor Type",
    type: "text",
    uiType: "select",
    uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
    options: ELIGIBLE_INVESTOR_TYPES,
  },
  {
    name: "investment_visibility",
    initailValue: "",
    label: "Investment Visibility",
    type: "text",
    uiType: "select",
    uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
    options: VISIBILITY_OPTIONS,
  },
];


export const OtherFormFields = (
  BORROWER_TYPES: any[]
): IFormField[] => [
  {
    name: "borrower_type",
    initailValue: "",
    label: "Borrower Type",
    type: "text",
    uiType: "text",
    uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
    options: BORROWER_TYPES,
  },
  {
    name: "isin_number",
    initailValue: "",
    label: "ISIN Number",
    type: "text",
    uiType: "text",
    uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
  },
  {
    name: "issuer_name",
    initailValue: "",
    label: "Issuer Name",
    type: "text",
    uiType: "text",
    uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
  },
  {
    name: "issuer_country",
    initailValue: "",
    label: "Issuer Country",
    type: "text",
    uiType: "text",
    uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
  },
  {
    name: "issuer_website",
    initailValue: "",
    label: "Issuer Website",
    type: "text",
    uiType: "text",
    uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
  },
  {
    name: "issuer_email",
    initailValue: "",
    label: "Issuer Email",
    type: "email",
    uiType: "email",
    uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
  },
  {
    name: "issuer_phone_number",
    initailValue: "",
    label: "Issuer Phone Number",
    type: "text",
    uiType: "text",
    uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
  },
  {
    name: "issuer_address",
    initailValue: "",
    label: "Issuer Address",
    type: "text",
    uiType: "text",
    uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
  },
  {
    name: "issuer_description",
    initailValue: "",
    label: "Issuer Description",
    type: "text",
    uiType: "textarea",
    uiBreakpoints: { xs: 12, sm: 12, md: 12, lg: 12, xl: 12 },
  },
  { 
    name: "issuer_registration_number",
    initailValue: "",
    label: "Issuer Registration Number",
    type: "text",
    uiType: "text",
    uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 }
  },
  {
    name: "issuer_tax_number",
    initailValue: "",
    label: "Issuer Tax Number",
    type: "text",
    uiType: "text",
    uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 }
  },
  {
    name: "issuer_logo",
    initailValue: "",
    label: "Issuer Logo",
    type: "file",
    uiType: "file",
    uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
  },
  {
    name: "credit_rating",
    initailValue: "",
    label: "Credit Rating",
    type: "text",
    uiType: "text",
    uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
  },
  {
    name: "esg_rating",
    initailValue: "",
    label: "ESG Rating",
    type: "text",
    uiType: "text",
    uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
  },
  {
    name: "loan_purpose",
    initailValue: "",
    label: "Loan Purpose",
    type: "text",
    uiType: "text",
    uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
  },
  {
    name: "investment_image",
    initailValue: "",
    label: "Investment Image",
    type: "file",
    uiType: "file",
    uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
  },
  {
    name: "terms_and_conditions",
    initailValue: "",
    label: "Terms and Conditions",
    type: "text",
    uiType: "textarea",
    uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
    multiline: true,
    rows: 3,
  },
  {
    name: "kyc_required",
    initailValue: false,
    label: "KYC Required",
    type: "boolean",
    uiType: "switch",
    uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
  },
];


// import { IFormField } from "../../../utils/form_factory";
// import { CURRENCY_CODES } from "../../../constants/currency-codes";
// import { IGeneralFormProps } from "../../Investments/InvestmentsList/Investment.interface";
// import { countries } from "../../../api/constants";

// export const GeneralFormFields = (props: IGeneralFormProps): IFormField[] => {
//   const { institutions, handleInstitutionSearch } = props;
//   return [
//     {
//       name: "name",
//       initailValue: "",
//       label: "Investment Name",
//       type: "text",
//       uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
//       uiType: "text",
//     },
//     {
//       name: "host_institution",
//       initailValue: "",
//       label: "Host Institution",
//       type: "text",
//       uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
//       uiType: "select",
//       options: institutions,
//       handleSearch: handleInstitutionSearch
//     },
//     {
//       name: "email",
//       initailValue: "",
//       label: "Contact Email Address",
//       type: "text",
//       uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
//       uiType: "text",
//     },
//     {
//       name: "address_line",
//       initailValue: "",
//       label: "Institution Address",
//       type: "text",
//       uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
//       uiType: "text",
//     },
//     {
//       name: "country",
//       initailValue: "",
//       label: "Country",
//       type: "text",
//       uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
//       uiType: "select",
//       options: countries,
//     },
//     {
//       name: "convenor_name",
//       initailValue: "",
//       label: "Convenor's Name",
//       type: "text",
//       uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
//       uiType: "text",
//     },
//     {
//       name: "primary_phone_number",
//       initailValue: "",
//       label: "Primary Phone Number",
//       uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
//       uiType: "phone",
//       customFormat: "XXX-XXX-XXXXXX",
//     },
//     {
//       name: "secondary_phone_number",
//       initailValue: "",
//       label: "Any Other Phone Number",
//       uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
//       uiType: "phone",
//       customFormat: "XXX-XXX-XXXXXX",
//     },
//     {
//       name: "start_date",
//       initailValue: "",
//       label: "Start Date",
//       uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
//       uiType: "date",
//     },
//     {
//       name: "end_date",
//       initailValue: "",
//       label: "End Date",
//       uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
//       uiType: "date",
//     },
//   ];
// };

// export const SettingsFormFields = (
//   DEBATE_FORMAT: any[],
//   DEBATE_LEVEL: any[],
//   AGE_GROUP: any[],
//   INVESTMENT_TYPE: any[],
//   INVESTMENT_STATUS: any[]
// ): IFormField[] => [
//   {
//     name: "type",
//     initailValue: "",
//     label: "Investment Type",
//     type: "text",
//     uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 4, xl: 4 },
//     uiType: "select",
//     options: INVESTMENT_TYPE,
//   },
//   {
//     name: "debate_level",
//     initailValue: "",
//     label: "Debate Level",
//     type: "text",
//     uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 4, xl: 4 },
//     uiType: "select",
//     options: DEBATE_LEVEL,
//   },
//   {
//     name: "debate_format",
//     initailValue: "",
//     label: "Debate Format",
//     type: "text",
//     uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 4, xl: 4 },
//     uiType: "select",
//     options: DEBATE_FORMAT,
//   },
//   {
//     name: "participants_age",
//     initailValue: "",
//     label: "Participants Age Group",
//     type: "text",
//     uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 4, xl: 4 },
//     uiType: "select",
//     options: AGE_GROUP,
//   },
//   {
//     name: "investment_currency",
//     initailValue: "",
//     label: "Currency",
//     type: "text",
//     uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 4, xl: 4 },
//     uiType: "select",
//     options: CURRENCY_CODES,
//   },
//   {
//     name: "registration_fee",
//     initailValue: "",
//     label: "Registration Fee",
//     type: "text",
//     uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 4, xl: 4 },
//     uiType: "number",
//   },
//   {
//     name: "number_of_rounds",
//     initailValue: "",
//     label: "Number of Rounds",
//     type: "number",
//     uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 4, xl: 4 },
//     uiType: "number",
//   },
//   {
//     name: "number_of_teams_in_outround",
//     initailValue: "",
//     label: "Number of teams in outrounds",
//     type: "number",
//     uiBreakpoints: { xs: 12, sm: 12, md: 6, lg: 4, xl: 4 },
//     uiType: "number",
//   }
// ];


// export const OtherFormFields = (): IFormField[] => [
//   {
//     name: "notes",
//     initailValue: "",
//     label: "About Investment",
//     type: "textarea",
//     uiBreakpoints: { xs: 12, sm: 12, md: 12, lg: 12, xl: 12 },
//     uiType: "textarea",
//     multiline: true,
//     rows: 3,
//   },
// ];
